config/routes.rb
Rails.application.routes.draw do
  resources :parks

  resources :parkings
  resources :reports do
    get "delete"
  end
  resources :members do
    get "delete"
    get "look"
  end
  resources :try_codes, only: [:new, :create, :index]
  resources :billings, only:[:new, :create, :index, :destroy, :show, :durate, :give_time] do
    
    member do
      patch 'stop'
    end
  end

  match '/angkat_portal' => 'billings#angkat_portal', via: :get
  match '/turunkan_portal' => 'billings#turunkan_portal', via: :get
  match '/give_time' => 'billings#give_time', via: :get
  match '/durate' => 'billings#durate', via: :get
  match '/buat_karcis' => 'billings#buat_karcis', via: :get
  
  match '/angkat_portal_parkir1' => 'parks#angkat_portal_parkir1', via: :get
  match '/turunkan_portal_parkir1' => 'parks#turunkan_portal_parkir1', via: :get
  
  

  root 'billings#new'

end

app/views/shared/_change_color.html.erb
<%= @color %>

app/views/shared/_durate.html.erb
<div class="time-detail"><%= @durate %></div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	  <%= link_to "Parkir Cerdas", root_path, class: 'navbar-brand' %>
      <!-- <a class="navbar-brand">Parkir Cerdas</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Cashier', billings_path %></li>
        <li><%= link_to 'Member', members_path %></li>
        <li><%= link_to 'Report', reports_path %></li>
        <li><%= link_to 'Parks', new_park_path %></li>
        <li><%#= link_to 'Parkings', new_parking_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Login</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_time_portion.html.erb
<div class="time-detail"><%= @time %></div>