config/routes.rb
Rails.application.routes.draw do
  resources :parks

  resources :parkings
  resources :reports do
    get "delete"
  end
  resources :members do
    get "delete"
    get "look"
  end
  resources :try_codes, only: [:new, :create, :index]
  resources :billings, only:[:new, :create, :index, :destroy, :show, :durate, :give_time] do
    
    member do
      patch 'stop'
    end
  end

  match '/angkat_portal' => 'billings#angkat_portal', via: :get
  match '/turunkan_portal' => 'billings#turunkan_portal', via: :get
  match '/give_time' => 'billings#give_time', via: :get
  match '/durate' => 'billings#durate', via: :get
  match '/buat_karcis' => 'billings#buat_karcis', via: :get
  
  match '/angkat_portal_parkir1' => 'parks#angkat_portal_parkir1', via: :get
  match '/turunkan_portal_parkir1' => 'parks#turunkan_portal_parkir1', via: :get
  
  

  root 'billings#new'

end

app/models/billing.rb
require 'barby'
require 'barby/barcode/ean_13'
require 'barby/barcode/code_39'
require 'barby/barcode/code_128'
require 'barby/outputter/html_outputter'
require 'barby/outputter/pdfwriter_outputter'
require 'barby/outputter/prawn_outputter'
# require 'barby/outputter/cairo_outputter'

# require "../pdfs/parkir_pdf"
# == Schema Information
#
# Table name: billings
#
#  id         :integer          not null, primary key
#  member_id  :integer
#  time_in    :datetime
#  time_out   :datetime
#  duration   :datetime
#  price      :decimal(, )
#  comment    :string
#  expiration :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Billing < ActiveRecord::Base
  has_many :parks
  belongs_to :member
  belongs_to :report
  
  accepts_nested_attributes_for :report
  before_create :set_expiration_date
  before_create :set_parking
  
  
  # attr_accessor :check_nama

  
  # before_update :copy_to_reports
  default_scope   -> {order('time_out DESC')}
  scope :current, -> {where('time_out IS NULL').order('time_in DESC')}
  scope :complete, -> {where('time_out IS NOT NULL').order('time_out DESC')}  
  scope :today, -> {where('time_in >= ? AND time_in <= ?', Time.now.beginning_of_day, Time.now.end_of_day).order('time_out DESC')}
  scope :expiration_date, -> {where('expiration <= ?', Date.today )}
  scope :park, -> {where('number_park IS NULL')}
  
  validates_presence_of :time_in, :member, message: 'Tidak Kosong'
  # validates_presence_of :number_park, message: 'Parkir sudah penuh'
  validate :check_time_in_and_out
  validate :check_current_billing_in_use, on: :create
  validate :check_number_park, on: :create

  
  #jika sudah ada user yang keluar dan maka parkir dibuat untuk mengisi kekosongan 
  def check_number_park
    if Billing.current.size == 9
            errors.add(:number_park, "Parkir Sudah Full Silahkan Datang Kembali Lain Waktu")
    end
    # if self.number_park.nil? #&& Billing.complete.where(:number_park => nil).present?
#       errors.add(:number_park, "Parkir Sudah Full Silahkan Datang Kembali Lain Waktu")
#     end
  end
  def check_time_in_and_out
    if self.time_out.present?
      errors.add(:time_out, "Waktu Keluar Muncul Setelah Waktu Masuk") if self.time_out.present? && self.time_out < self.time_in
    end
  end
   
   #jika sudah ada user yang parkir dan belum keluar maka tidak dapat mebuat billing baru  
  def check_current_billing_in_use
    if Billing.current.where(:member_id => member_id).present? 
      errors.add(:base, 'Tidak Dapat Membuat Billing Baru Jika Ada Billing Sebelumnya Yang Belum Di Tutup')   
    end 
  end
  
  def stop!
    if self.time_out.nil?
      update_attributes(time_out: Time.now)#("#{self.time_out}".to_i - "#{self.time_in}".to_i))
      true
    else
      false
    end
  end
  
  def self.time_today
    sum = 0.0
    self.today.each {|e| sum += (e.time_out.nil ? Time.now : e.time_out) - e.time_in }
  end
  
  def set_expiration_date
    tomorrow = Date.today + 1.day
    self.expiration = tomorrow
  end
  
  
  def self.tomorrow
    @tomorrow = Date.today + 1.day
  end
  
  def self.copy_to_reports
    Billing.expiration_date.complete.find_each do |billing|
         Report.create(:date  => "#{billing.expiration}", :billing_id  => "#{billing.id}", :member_id  => "#{billing.member_id}", :time_in  => "#{billing.time_in}", :time_out  => "#{billing.time_out}", :duration  => "#{billing.duration}", :comment  => "#{billing.comment}", :price  => "#{billing.price}") 
         billing.destroy  
    end
  end
  
  def set_parking
    a = [1,2,3,4,5,6,7,8,9]
    b = Billing.current.pluck(:number_park)
    c = a - b
    self.number_park = c.first    
  end 
  
  def barcode
    @barcode = Barby::Code128B.new(self.number_park)
  end
  
end

app/controllers/billings_controller.rb
require "prawn"
class BillingsController < ApplicationController
  before_action :set_up_led, only: [:angkat_portal, :turunkan_portal, :create]
  before_action :set_billing, only: [ :show, :edit, :update, :destroy]

  # GET /billings
  # GET /billings.json
  def index
    @portal_terangkat = params[:portal_terangkat]
    @billings = Billing.all.page(params[:page]).per_page(9)
    @billing = Billing.current.find(params[:id]) unless @Billings.nil?
    respond_to do |format|
      format.js
      format.html
      format.pdf do
        send_data generate_pdf,
                              type: "application/pdf",
                              disposition: "inline",
                              filename: "#{@billing.id}.pdf"
      end
    end
  end

  # GET /billings/1
  # GET /billings/1.json
  def show
    @portal_terangkat = params[:portal_terangkat]
    @barcode = Barby::HtmlOutputter.new(@billing.barcode)
    # @barcode = Barby::CairoOutputter.new(@billing.barcode)
        # @doc = barcode.annotate_pdf(self)
    # @doc = @barcode.to_pdf
    respond_to do |format|
      format.html
      # format.js
      # format.json{render json: @billing}
      format.pdf do
        send_data generate_pdf,
                              type: "application/pdf",
                              disposition: "inline",
                              filename: "#{@billing.id}.pdf"
      end
    end
  end

  # GET /billings/new
  def new
    @billing = Billing.new
  end



  # GET /billings/1/edit
  # def edit
#   end

  # POST /billings
  # POST /billings.json
  def create
    @billing = Billing.new(billing_params)
    respond_to do |format|
      # format.html { render :new }
      # format.json { render json: @billing.errors, status: :unprocessable_entity }
      if @billing.save
        # @servo.on
        @servo.position = 0
        # format.html { render :show, :portal_terangkat => true, notice: 'Billing Berhasil Dibuat.' }
        format.html { redirect_to billings_path(:portal_terangkat => true), notice: 'Billing Berhasil Dibuat.' }
        # format.json { render :show, status: :created, location: @billing }
        # format.json { render :new }

      else
                # @servo.off
        @servo.position = 100
        format.html { render :new, :portal_terangkat => false }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /billings/1
  # PATCH/PUT /billings/1.json
  # def update
#     respond_to do |format|
#       # if @billing.update_attributes(params[:time_in, :comment, :expiration])
#       if @billing.update(billing_params)
#         format.html { redirect_to @billing, notice: 'Billing was successfully updated.' }
#         # format.json { render :show, status: :ok, location: @billing }
#         format.json { render :new }
#       else
#         format.html { render :edit }
#         format.json { render json: @billing.errors, status: :unprocessable_entity }
#       end
#     end
#   end

  # DELETE /billings/1
  # DELETE /billings/1.json
  def destroy
    @billing.destroy
    respond_to do |format|
      format.html { redirect_to billings_url, notice: 'Billing Berhasil Dihapus.' }
      format.json { head :no_content }
    end
  end

  def stop
    @billing = Billing.find(params[:id])
    # @billing.stop!
    if @billing.stop!
      respond_to do |format|
        format.html {redirect_to @billing, notice: 'Billing stopped'}
        format.js
        format.json{render json: @billing}
      end
    else
      respond_to do |format|
        format.html {redirect_to billings_url, notice: 'Billing was already stopped'}
      end
    end
  end

  def angkat_portal
    @servo.position = 0
    # @servo.on
    sleep 0.1
    render :nothing => true
  end

  def turunkan_portal
    @servo.position = 100
    # @servo.off
    sleep 0.1
    render :nothing => true
  end

  # def pretty_duration
  #   parse_string =
  #       if self < 3600
  #           '%M:%S'
  #       else
  #           '%H:%M:%S'
  #       end
  #
  #   Time.at(self).utc.strftime(parse_string)
  # end

  def give_time
    @time = Time.now.strftime(" %H:%M:%S ")

    render :partial => 'shared/time_portion'
  end

  def durate
        @billing = Billing.find(params[:id])
        @selisih_waktu = Time.now - @billing.time_in
        @durate = @selisih_waktu.to_i.pretty_duration
        render :partial => 'shared/durate'
  end


  private
    # Use callbacks to share common setup or constraints between actions.

    def generate_pdf 
      pdf = ParkirPdf.new(@billing)
      pdf.render
    end

    def set_billing
      @billing = Billing.find(params[:id])
    end

    def set_up_led
      # Arduino::Application.config.board
      # Dino::Board.new(Dino::TxRx.new)

      @board = Dino::Board.new(Dino::TxRx.new)
            @servo = Dino::Components::Servo.new(pin: 12, board: @board )
            # @servo = Dino::Components::Led.new(pin: 12, board: @board)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def billing_params
      params.require(:billing).permit(:member_id, :time_in, :time_out, :price, :comment, :duration, :expiration, :number_park, :reports_attributes => [:id, :date, :time_in, :time_out, :duration, :price, :comment, :member_id, :billing_id] )
    end

end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/views/billings/_billing.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Parkir Nomor  <%= @billing.number_park %> Selesai</h3>   
  </div>
  <div class="modal-body">
  <% selisih_waktu = (Time.parse(@billing.time_out.to_s) - Time.parse(@billing.time_in.to_s))%>    
  <p><strong>Lama Parkir:&nbsp;</strong> <%=  selisih_waktu.to_i.pretty_duration    %></p>
  <h1>
    <strong>Biaya:&nbsp;</strong>
    Rp <%= 2000 + number_with_precision(selisih_waktu/1800, precision: 2).to_i * 1000 %>
  </h1>
  <p>
    <strong>Member:&nbsp;</strong>
    <%= @billing.member.name %>
  </p>

  <p>
    <strong>Waktu Masuk:&nbsp;</strong>
    <%= @billing.time_in.strftime("%H:%M:%S") %>
  </p>

  <p>
    <strong>Waktu Keluar:&nbsp;</strong>
    <%= @billing.time_out.strftime("%H:%M:%S") %>
  </p>
  <ul class="errors"></ul>
    
  </div>
  <div class="modal-footer">
    <%= link_to "Close", billings_path, class: "btn btn-default" %>
  </div>
  </div>
</div>

app/views/billings/_current.html.erb
<% current_billings.each do |bill| %>
	<div class="time">
		<%= number_with_precision((Time.now - bill.time_in)/3600, precision: 2) %>
  	</div>
<% end %>

app/views/billings/_form.html.erb
      <div class="row">
        <div class="col-sm-12 col-md-8">
        <%= form_for(@billing, :html => { class:"form-horizontal", role:"form"}) do |f| %>
          <% if @billing.errors.any? %>
          <div id="flash">
            <div id="error_explanation">
              <h4><%= @billing.errors.count %> Kesalahan, Tidak Dapat Menyimpan Billing Yang Dibuat Karena:</h4>

              <ul>
              <% @billing.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          </div>
     
          <% end %>
        <div class=form-group>
          <h3>Selamat Datang</h3>
          <h1>Silahkan Scan Member Card Anda</h1>
        </div>
         
        
       	<div class="form-group">
            <% f.label :member_id, "Nama", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight" %>
            <div class="col-sm-8 col-md-5"><%= f.collection_select(:member_id, Member.all, :id, :id, {include_blank:""}, class:"form-control weight", id:"inputmember", autofocus: true ) %> </div>
          </div>
	
          <div class="form-group">
            <% f.label :time_in, "Waktu Masuk", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight" %><br>
            <div class="col-sm-8 col-md-5"><%= f.datetime_select :time_in, class:"form-control weight", id:"inputText3", include_seconds: true %></div>
          </div>
      	<% if !@billing.new_record? %>
          <div class="form-group">
            <% f.label :time_out, "Waktu Keluar", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight" %><br>
            <div class="col-sm-8 col-md-5"><% f.datetime_select :time_out, class:"form-control weight", id:"inputText3", include_seconds: true %></div>
          </div>
      	<% end %>
    
          <div class="form-group">
            <% f.label :comment, "Komentar", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight" %><br>
            <div class="col-sm-8 col-md-5"><% f.text_field :comment, class:"form-control weight", id:"inputText3" %></div>
          </div>
	
	
          <div class="form-group">
            <div class="col-sm-offset-3 col-sm-3 col-md-offset-3">
               <%= action_name == "new"? (f.submit "Buat Billing", class:"btn btn-success"):(f.submit "Buat Billing", class:"btn btn-success") %>
            </div>
          </div>
            
          
          <%= link_to "Index", billings_path, class: "btn" %>
        <% end %>
        </div>
        </div>
        <div class="col-sm-12 col-md-4">
          <% if Billing.present? %>
          <h3>Jumlah Parkir Tersedia</h3>
          <h1><%= Billing.current.count %></h1>
          <% elsif Billing.current.count == 9 %>
          <h3>Maaf Parkir Sudah Full Silahkan Datang Lain Kali</h3>
          <% else %>
          <h3>Belum Ada Yang Parkir</h3>
          <% end %>
        </div>
      </div>

 

app/views/billings/_index.html.erb
    			    <% @billings.each do |billing| %>
    			      <tr>
			        
                  <td><%= link_to billing.number_park, billing %></td>
                  <td><%= billing.member.name %></td>
    			        <td><%= billing.time_in.strftime("%H:%M:%S")%></td>

    					    <% unless billing.time_out.nil? %>
    					    <% selisih_waktu = (Time.parse(billing.time_out.to_s) - Time.parse(billing.time_in.to_s))%>
    					    <td><%= billing.time_out.strftime("%H:%M:%S")%></td>
    			        <td><%=  selisih_waktu.to_i.pretty_duration    %></td>
    			        <td>Rp <%= number_with_precision(selisih_waktu/3600, precision: 2).to_i * 1000 %></td>
    					    <% else %>
    					    <td class="time"></td>
    					    <%# durasi = (Time.parse(Time.now.to_s) - Time.parse(billing.time_in.to_s))%>
    					    <td class= "counter" data-id="<%= billing.id %>"> <%#= render partial: 'shared/duration' %>  <%#= durasi.to_i.pretty_duration %></td>
    					    <td></td>
    					    <% end %>
                  <td><%= billing.expiration.strftime("%D")%></td>
				   
    			        <td>
                    <%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden="true"data-toggle="tooltip" data-placement="top" title="Hapus"></span>'.html_safe, billing, method: :delete, data: { confirm: 'Are you sure?' } %>
                  		</td>
                      <td><%= link_to 'Stop', stop_billing_path(billing), remote: true, class: 'btn btn-danger', method: :patch if billing.time_out.nil? %></td>
    			      </tr>
    			    <% end %>

app/views/billings/_new.html.erb
  <%= render 'form' %>
  
  <div id="billing-modal" class="modal fade"></div>

<%#= link_to '<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"data-toggle="tooltip" data-placement="top" title="Index"></span> Index'.html_safe, billings_path, class: 'btn btn-default' %>


	

app/views/billings/_parkir.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Parkir Nomor <%= @billing.number_park %> </h3>   
  </div>
  <div class="modal-body">
  <p>
    <strong>Member:&nbsp;</strong>
    <%= @billing.member.name %>
  </p>

  <p>
    <strong>Waktu Masuk:&nbsp;</strong>
    <%= @billing.time_in.strftime("%H:%M:%S") %>
  </p>
  <ul class="errors"></ul>
    
  </div>
  <div class="modal-footer">
    <%= link_to "Close", billings_path, class: "btn btn-default" %>
		
  </div>
  </div>
</div>

<script>
$(document).ready(function(){  
  
  
  var portal_terangkat = <%= @portal_terangkat == 'true' ? 'true' : 'false' %>;
  if(portal_terangkat){
      window.setTimeout(function(){
        $.ajax({
          url: '<%= turunkan_portal_path %>';
        });
      }, 3000);
    }
  
 
})
  
</script>

app/views/billings/close.js.erb
$("ul.errors").html("")
<% if @billing.errors.any? %>
  <% @billing.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".billing-index").html("<%= escape_javascript(render 'index') %>")
  $("#billing-modal").modal("hide")
<% end %>

app/views/billings/edit.html.erb
	<h3>Edit Billing</h1>

	<%= render 'form' %>
	
	<%= link_to 'Lihat', @billing, class:'btn btn-default' %> 
	<%= link_to 'Kembali', billings_path, class:'btn btn-primary' %>

app/views/billings/index.html.erb
<% if @billings.present? %>
<div class="row">
	<div class="col-md-12">
		<h3>Billing : <span class="time-rect-container"></span></h3>
	</div>	
</div>




<div class="row">
	<div class="col-md-12"><%= link_to '+ Buat Billing', new_billing_path, class: 'btn' %>
    <%#= link_to 'Portal', root_path, class: 'btn btn-default' %>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading"></div>
    			<table class="table table-hover table-striped">
    			  <thead>
    			    <tr>     
                <th>Parkir No</th>
                <th>Member</th>
    			      <th>Jam Masuk</th>
    			      <th>Jam Keluar</th>
    			      <th>Lama</th>
    			      <th>Biaya</th>
    				    <th>Masa Berlaku</th>
    			      <th colspan="2">Option</th>
    			    </tr>
    			  </thead>

    			  <tbody class="billing-index">
    			   <%= render "index" %>
    			  </tbody>
    			</table>
          <div id="billing-modal" class="modal fade"></div>
			<br>
			<div class="panel-footer">
				<button id="angkat_portal", class="btn btn-default"><span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>  Angkat</button>
									<button id="turunkan_portal", class="btn btn-success"><span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>  Turunkan</button>
			</div>
		</div>

	</div>
	<div class="col-xs-12 col-sm-12 col-md-12"><center><%= will_paginate @billings, renderer: BootstrapPagination::Rails %></center></div>
</div>




<% else %>
<div class="row">
	<div class="col-md-12">
		<h3>Billing Hari Ini Belum Ada, Silahkan Menunggu.. </h3>
	</div>	
</div>
<% end %>


<script = "text/javascript">  
  $(document).ready(function(){
    var portal_terangkat = <%= @portal_terangkat == 'true' ? 'true' : 'false' %>
    if(portal_terangkat){
        window.setTimeout(function(){
          // setInterval(function(){
          $.ajax({
            url: '<%= turunkan_portal_path %>'
          });
        }, 3000);
      }
  });
</script>
  
  

app/views/billings/new.html.erb
  <%= render 'form' %>
  
  

<%#= link_to '<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"data-toggle="tooltip" data-placement="top" title="Index"></span> Index'.html_safe, billings_path, class: 'btn btn-default' %>


	

app/views/billings/new.js.erb
// $("#billing-modal").html("<%= escape_javascript(render 'new') %>")
// $("#billing-modal").modal('show')

app/views/billings/show.html.erb
<%#= render "parkir" %>

<h3>Harap Parkir Di Nomor <%= @billing.number_park %> </h3>   
  <p>
    <strong>Member:&nbsp;</strong>
    <%= @billing.member.name %>
  </p>

  <p>
    <strong>Waktu Masuk:&nbsp;</strong>
    <%= @billing.time_in.strftime("%H:%M:%S") %>
  </p>
  
  <%= raw @barcode.to_html %>
  <ul class="errors"></ul>

<% url = "#{@billing}.pdf" %> 
<iframe id ="pdf_source" src="<%= url %>" style="width:700px;height:500px;"></iframe>

<script>
   var portal_terangkat = <%= @portal_terangkat == 'true' ? 'true' : 'false' %>;
   if(portal_terangkat){
       window.setTimeout(function(){
         $.ajax({
           url: '<%= turunkan_portal_parkir1_path %>';
         });
       }, 3000);
    }
</script>

 

app/views/billings/show.js.erb
// $("#billing-modal").html("<%= escape_javascript(render 'parkir') %>")
// $("#billing-modal").modal('show')

// $(document).ready(function(){
//   pdf = document.getElementById('pdf_source');
//   pdf.focus();
//
//   setTimeout(function(){
//       pdf.contentWindow.print();
//   }, 3000);
// });

app/views/billings/stop.js.erb
$("#billing-modal").html("<%= escape_javascript(render 'billing') %>")
$("#billing-modal").modal('show')