config/routes.rb
Rails.application.routes.draw do
  resources :parks

  resources :parkings
  resources :reports do
    get "delete"
  end
  resources :members do
    get "delete"
    get "look"
  end
  resources :try_codes, only: [:new, :create, :index]
  resources :billings, only:[:new, :create, :index, :destroy, :show, :durate, :give_time] do
    
    member do
      patch 'stop'
    end
  end

  match '/angkat_portal' => 'billings#angkat_portal', via: :get
  match '/turunkan_portal' => 'billings#turunkan_portal', via: :get
  match '/give_time' => 'billings#give_time', via: :get
  match '/durate' => 'billings#durate', via: :get
  match '/buat_karcis' => 'billings#buat_karcis', via: :get
  
  match '/angkat_portal_parkir1' => 'parks#angkat_portal_parkir1', via: :get
  match '/turunkan_portal_parkir1' => 'parks#turunkan_portal_parkir1', via: :get
  
  

  root 'billings#new'

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id         :integer          not null, primary key
#  date       :date
#  billing_id :integer
#  member_id  :integer
#  time_in    :datetime
#  time_out   :datetime
#  duration   :datetime
#  comment    :string
#  price      :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Report < ActiveRecord::Base
  has_many :billings
  has_many :members, through: :billings
  private
    def self.search(query)
        where("lower(comment) like ?", "%#{query}%") 
    end 
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.search(params[:search]).page(params[:page]).per_page(6).order('created_at desc')
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def delete
    @report = Report.find(params[:report_id])
  end
  
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:date, :billing_id, :member_id, :time_in, :time_out, :duration, :price, :comment, :members_attributes[], :billings_attributes[])
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Hapus Report</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Apakah Anda Ingin Menghapus Report <b><%= @report.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Ya, Hapus Report Ini", report_path(@report), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "Tidak", "#", class: "btn btn-default",  data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/reports/_edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3>Edit Laporan</h3>
    </div>
    <div class="modal-body">
      <%= render 'form' %>
    </div>
    <div class="modal-footer">
      <%= link_to 'Show', @report, remote: true, class: 'btn btn-primary' %> 
      <%= link_to 'Tutup', '#', remote:true, data:{dismiss: 'modal'}, class: 'btn' %>
    </div>
  </div>
</div>

app/views/reports/_form.html.erb
      <%= form_for(@report, remote: true) do |f| %>
        <% if @report.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

            <ul>
            <% @report.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :date %><br>
          <%= f.datetime_select :date %>
        </div>
  
        <div class="field">
          <%= f.label :billing_id %><br>
          <%= f.number_field :billing_id %>
        </div>
        <div class="field">
          <%= f.label :member_id %><br>
          <%= f.text_field :member_id %>
        </div>
        <div class="field">
          <%= f.label :time_in %><br>
          <%= f.text_field :time_in %>
        </div>
        <div class="field">
          <%= f.label :time_out %><br>
          <%= f.text_field :time_out %>
        </div>
        <div class="field">
          <%= f.label :duration %><br>
          <%= f.text_field :duration %>
        </div>
        <div class="field">
          <%= f.label :price %><br>
          <%= f.text_field :price %>
        </div>
        <div class="field">
          <%= f.label :comment %><br>
          <%= f.text_area :comment, row: 3 %>
        </div>
  
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
      
   

app/views/reports/_index.html.erb
			    <% @reports.each do |report| %>
			      <tr>
					  <td><%= report.date.strftime('%d - %m - %Y') %></td>
			        <td><%= report.billing_id%></td>
			        <td><%= report.member_id %></td>
					<td><%= report.time_in.strftime("%T") %></td>
			        <td><%= report.time_out.strftime("%T") if report.time_out  %></td>
					<td>
						<% selisih_waktu = (Time.parse(report.time_out.to_s) - Time.parse(report.time_in.to_s))%>
						<%=  selisih_waktu.to_i.pretty_duration    %>
					</td>
					<td>Rp <%= number_with_precision(selisih_waktu/3600, precision: 2).to_i * 1000 %></td>
					<td><%= report.comment %></td>
					<td><%= report.price %></td>
			        <td><%= link_to '<span class="glyphicon glyphicon-edit" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Edit"></span>'.html_safe, edit_report_path(report), remote: true %></td>
			        <td><%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden="true"data-toggle="tooltip" data-placement="top" title="Hapus"></span>'.html_safe, report_delete_path(report), remote: true %></td>
			      </tr>
			    <% end %>

app/views/reports/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3>Buat Laporan</h3>
    </div>
    <div class="modal-body">
      <%= render 'form' %>
    </div>
    <div class="modal-footer">
      <%= link_to 'Tutup', '#', remote:true, data:{dismiss: 'modal'}, class: 'btn' %>
    </div>
  </div>
</div>

app/views/reports/_save.js.erb
$("ul.errors").html("")
<% if @report.errors.any? %>
  <% @report.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".report-index").html("<%= escape_javascript(render 'index') %>")
  $("#report-modal").modal("hide")
<% end %>

app/views/reports/create.js.erb
<%= render 'save'%>

app/views/reports/delete.js.erb
$("#report-modal").html("<%= escape_javascript(render 'delete') %>")
$("#report-modal").modal("show")

app/views/reports/destroy.js.erb
<%= render "save" %>

app/views/reports/edit.js.erb
$("#report-modal").html("<%= escape_javascript(render 'edit') %>")
$("#report-modal").modal("show")

app/views/reports/index.html.erb
<% if @reports.present? %>
<div class="row">
	<div class="col-md-12"><h3>Laporan Transaksi Billing</h3></div>
	
</div>

<div class="row">
	<div class="col-md-12"><%= link_to 'Laporan Baru', new_report_path, remote: true, class: 'btn btn-default' %>
    <%= form_tag reports_path, :method => 'get', :id => "search",class:'navbar-form navbar-right', role: 'search' do%>
    <div class="form-group">
      <div class="col-xs-6 col-sm-4 col-md-4">
        <%= text_field_tag :search, params[:search], class:'form-control', placeholder:'Cari..' %>
      </div>
      <%= submit_tag "Cari", :comment => nil, class:'btn btn-success col-xs-offset-0 col-xs-2 col-sm-offset-5 col-sm-3 col-md-offset-5 col-md-3' %>
    </div>    
    <% end %>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading"></div>
			<table class="table table-hover table-striped">
			  <thead>
			    <tr>
			      <th>Tanggal</th>
			      <th>Billing</th>
				  <th>Member</th>
			      <th>Waktu Masuk</th>
			      <th>Waktu Keluar</th>
			      <th>Lama Parkir</th>
				  <th>Harga</th>
				  <th>Keterangan</th>
			      <th colspan="2"></th>
			    </tr>
			  </thead>

			  <tbody class="report-index">
			    <%= render 'index' %>
			  </tbody>
			</table>
			<br>
      <div id="report-modal" class="modal fade"></div>
		</div>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-12"><center><%= will_paginate @reports, renderer: BootstrapPagination::Rails %></center></div>
</div>

<% else %>
<div class="row">
	<div class="col-md-12"><h3>Belum Ada Laporan Yang Diterima</h3></div>
	
</div>
<% end %>

app/views/reports/new.js.erb
$("#report-modal").html("<%= escape_javascript(render 'new') %>")
$("#report-modal").modal("show")

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @report.date %>
</p>

<p>
  <strong>Member:</strong>
  <%#= @report.member.name %>
</p>

<p>
  <strong>Time in:</strong>
  <%= @report.time_in %>
</p>

<p>
  <strong>Time out:</strong>
  <%= @report.time_out %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @report.duration %>
</p>

<p>
  <strong>Price:</strong>
  <%= @report.price %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>

app/views/reports/update.js.erb
<%= render 'save'%>