config/routes.rb
Rails.application.routes.draw do
  resources :parks

  resources :parkings
  resources :reports do
    get "delete"
  end
  resources :members do
    get "delete"
    get "look"
  end
  resources :try_codes, only: [:new, :create, :index]
  resources :billings, only:[:new, :create, :index, :destroy, :show, :durate, :give_time] do
    
    member do
      patch 'stop'
    end
  end

  match '/angkat_portal' => 'billings#angkat_portal', via: :get
  match '/turunkan_portal' => 'billings#turunkan_portal', via: :get
  match '/give_time' => 'billings#give_time', via: :get
  match '/durate' => 'billings#durate', via: :get
  match '/buat_karcis' => 'billings#buat_karcis', via: :get
  
  match '/angkat_portal_parkir1' => 'parks#angkat_portal_parkir1', via: :get
  match '/turunkan_portal_parkir1' => 'parks#turunkan_portal_parkir1', via: :get
  
  

  root 'billings#new'

end

app/models/member.rb
require 'barby'
require 'barby/barcode/ean_13'
require 'barby/barcode/code_39'
require 'barby/barcode/code_128'

# == Schema Information
#
# Table name: members
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  phone      :string
#  barcode    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Member < ActiveRecord::Base
  default_scope -> {order('created_at desc')}
  validates :name, format: { with: /\A[a-zA-Z]+\z/, message: "Nama Depan/Panggilan Dengan Huruf Saja" }, length: { minimum: 3, message: "Nama Terlalu Pendek"  }
  validates :address, length: { minimum: 4, message: "Alamat Terlalu Pendek" }
  validates :phone, numericality: { only_integer: true, message: "Masukkan Hanya Angka Saja" }, length: { minimum: 10, message: "No Telepon Terlalu Pendek" }
  has_many :billings
  has_many :reports, through: :billings
  
  def barcode
    @barcode = Barby::Code128B.new(self.id)
  end
  
  private
    def self.search(query)
        where("lower(name) like lower(?) or phone like ? ", "%#{query}%", "%#{query}%") 
    end 
  
end

app/controllers/members_controller.rb
require 'chunky_png'
require 'rmagick'
require 'barby'
require 'barby/barcode/ean_13'
require 'barby/barcode/code_39'
require 'barby/barcode/code_128'
require 'barby/barcode/qr_code'
require 'barby/outputter/ascii_outputter'
require 'barby/outputter/rmagick_outputter'
require 'barby/outputter/html_outputter'
require 'barby/outputter/png_outputter' 
require 'barby/outputter/pdfwriter_outputter'


class MembersController < ApplicationController
  before_action :set_member, only: [:edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.search(params[:search]).page(params[:page]).per_page(6)
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /members/1
  # GET /members/1.json
  def look
    @member = Member.find(params[:member_id])
    barcodex = Barby::HtmlOutputter.new(@member.barcode).to_html  
    # barcodexpdf.annotate_pdf(doc)
    @barcode_for = barcodex
    respond_to do |format|
      format.html
      format.js
      format.pdf do
        # pdf = MemberPdf.new(@member)
        # send_data pdf.render,
        send_data generate_pdf,
                              type: "application/pdf",
                              disposition: "inline",
                              filename: "Form_#{@member.name}.pdf"
      end
    end
  end
  def show
    @member = Member.find(params[:id])
    # @barcode = Barby::Code128B.new(@member.id)
    barcodex = Barby::HtmlOutputter.new(@member.barcode).to_html  
    # barcodexpdf.annotate_pdf(doc)
    @barcode_for = barcodex
    respond_to do |format|
      format.html
      format.pdf do
        # pdf = MemberPdf.new(@member)
        # send_data pdf.render,
        send_data generate_pdf,
                              type: "application/pdf",
                              disposition: "inline",
                              filename: "Form_#{@member.name}.pdf"
      end
    end
  end

  # GET /members/new
  def new
    @member = Member.new
    
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    respond_to do |format|
      if @member.save
        format.html { redirect_to members_path, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render 'new', method: :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to members_path, notice: 'Member Berhasil Diupdate.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render 'edit' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def delete
    @member = Member.find(params[:member_id])
  end
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member Berhasil Dihapus.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def generate_pdf
      pdf = MemberPdf.new(@member)
      pdf.render
      # pdf.autoprint
    end
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :address, :phone, :barcode)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Hapus Member</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Apakah Anda Ingin Menghapus Member <b><%= @member.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Ya, Hapus Member Ini", member_path(@member), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "Tidak", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/members/_edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3>Edit Member</h3>
    </div>

      <%= render 'form' %>
        <%#= link_to 'Show', @member %> 

   
  </div>
</div>

app/views/members/_form.html.erb
    
    <%= form_for @member, :html => { class:"form-horizontal", role:"form"} do |f| %>

    <div class="modal-body">

        <% if @member.errors.any? %>
          <div id="error_explanation">
            <h4><%= @member.errors.count %> Kesalahan, Tidak Dapat Menyimpan Billing Yang Dibuat Karena:</h4>

            <ul>
            <% @member.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
     	<div class="form-group">
          <%= f.label :name, "Nama", for: "inputText3", class:"col-xs-12 col-sm-3 col-md-3 control-label weight" %>
    	  <div class="col-xs-8 col-sm-5 col-md-5"><%= f.text_field :name, class:"form-control weight", id:"inputText3" %></div>
      </div>
	
     	<div class="form-group">
          <%= f.label :address, "Alamat", for: "inputText3", class:"col-xs-12 col-sm-3 col-md-3 control-label weight" %>
    	  <div class="col-xs-8 col-sm-5 col-md-5"><%= f.text_field :address, class:"form-control weight", id:"inputText3" %></div>
      </div>
	
     	<div class="form-group">
          <%= f.label :phone, "Telepon", for: "inputText3", class:"col-xs-12 col-sm-3 col-md-3 control-label weight" %>
    	  <div class="col-xs-8 col-sm-5 col-md-5"><%= f.text_field :phone, class:"form-control weight", id:"inputText3" %></div>
      </div>
    </div>
	       
    <div class="modal-footer">
    	
      <%= action_name == "new" ? (f.submit "Buat Member", remote: true, class:"btn btn-success"):(f.submit "Edit Member",  remote: true, class:"btn btn-success") %>
         
      <%= link_to 'Tutup','#', class: 'btn', data: {dismiss: 'modal'} %>
    </div>
    <% end %>

app/views/members/_index.html.erb
				    <% @members.each do |member| %>
				      <tr>
						    <% member.barcode %>  
				        <td><%= link_to member.name.titleize, member_look_path(member), remote: true %></td>
				        <td><%= member.address.titleize %></td>
				        <td><%= member.phone %></td>
				        <td><%= link_to '<span class="glyphicon glyphicon-edit" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Edit"></span>'.html_safe, edit_member_path(member), remote: true %></td>
				        <td><%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden="true"data-toggle="tooltip" data-placement="top" title="Hapus"></span>'.html_safe, member_delete_path(member), remote: true %></td>
				      </tr>
				    <% end %>

app/views/members/_look.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-body">
      
        	<div class="panel panel-default">
        	  <div class="panel-heading">
        	    <h3 class="panel-title">Member Parkir</h3>
        	  </div>
          	  <ul class="list-group">
          	    <li class="list-group-item"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;&nbsp;&nbsp;<%= @member.name.titleize %></li>
          	    <li class="list-group-item"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;&nbsp;&nbsp;<%= @member.address.titleize %></li>
          	    <li class="list-group-item"><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span>&nbsp;&nbsp;&nbsp;<%= @member.phone %></li>
        		<li class="list-group-item"><%= raw (@barcode_for) %></li>
          	  </ul>
        	  <div class="panel-footer">
        		  <%= link_to 'Edit', edit_member_path(@member), remote: true, class: 'btn btn-default' %> 
        		  <%= link_to 'Kembali', '#', class: 'btn btn-success', data: {dismiss: 'modal'} %>
        		  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        		  <%= link_to "Cetak ID Card", member_path(@member, format:"pdf"), class:"btn btn-primary", :target  => "_blank" %>
        	  </div>
        	</div>
	
       
      </div>
    </div>
</div>
        

app/views/members/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3>Buat Member</h3>
    </div>
      <%= render 'form' %>
        <%#= link_to 'Show', @member %> 
</div>

app/views/members/_save.js.erb
$("ul.errors").html("")
<% if @member.errors.any? %>
  <% @member.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".member-index").html("<%= escape_javascript(render 'index') %>")
  $("#member-modal").modal("hide")
<% end %>

app/views/members/delete.js.erb
$("#member-modal").html("<%= escape_javascript(render 'delete') %>")
$("#member-modal").modal("show")

app/views/members/destroy.js.erb
<%= render "save" %>

app/views/members/edit.js.erb
$("#member-modal").html("<%= escape_javascript(render 'edit') %>")
$("#member-modal").modal("show")

app/views/members/index.html.erb
<% if @members.present? %>

	<div class="row">
		<div class="col-md-12"><h3>Daftar Member</h3></div>
		
	</div>
	
    
	
	<div class="row">
		<div class="col-md-12">
			<%= link_to 'Buat Member', new_member_path, remote: true, class: 'btn btn-default' %>
		    <%= form_tag members_path, :method => 'get', :id => "search",class:'navbar-form navbar-right', role: 'search' do%>
		    <div class="form-group">
		      <div class="col-xs-6 col-sm-4 col-md-4">
		        <%= text_field_tag :search, params[:search], class:'form-control', placeholder:'Cari..' %>
		      </div>
		      <%= submit_tag "Cari", :name => nil, class:'btn btn-success col-xs-offset-0 col-xs-2 col-sm-offset-5 col-sm-3 col-md-offset-5 col-md-3' %>
		    </div>    
		    <% end %>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-success">
				<div class="panel-heading"></div>
				<table class="table table-hover table-striped">
				  <thead>
				    <tr>
				      <th>Nama</th>
				      <th>Alamat</th>
				      <th>Telepon</th>    
				      <th colspan="2"></th>
				    </tr>
				  </thead>

				  <tbody class="member-index">
				    <%= render 'index' %>
				  </tbody>
				</table>
				<br>
			</div>
      <div id="member-modal" class="modal fade"></div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12"><center><%= will_paginate @members, renderer: BootstrapPagination::Rails %></center></div>
	</div>


<% else %>
	<div class="row">
		<div class="col-md-12"><h3>Member Tidak Ditemukan. </h3></div>
		<div class="col-md-12"><%= link_to 'Kembali', members_path, class: 'btn btn-default' %></div>
	</div>
<% end %>

	    <%#= link_to 'Portal', root_path, class: 'btn btn-default' %>
	
	

	

app/views/members/index.js.erb
$(".member-index").html("<%= escape_javascript(render 'index') %>")

app/views/members/look.js.erb
$("#member-modal").html("<%= escape_javascript(render 'look') %>")
$("#member-modal").modal("show")

app/views/members/update.js.erb
<%= render 'save' %>